import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { skillEffective, type ConsoleStateLike } from "./skills";
import { loadInternalSkills, loadWorkflowCatalog } from "./workflows/catalog";
import { skillBoundTo } from "./workflows/skills";

/**
 * Синк harness-команд в нативные каталоги команд и навыков рантаймов обязательной
 * рабочей папки: master-навыки и workflow становятся доступны в отдельно запущенном
 * рантайме как слэш-команды (/master:<id>, /workflow:<id>; у плоских рантаймов -
 * /master-<id>, /workflow-<id>; у codex и kimi команды доставляются навыками -
 * "/<имя>" и "/skill:<имя>"; общие /master и /workflow выбирают id из аргументов).
 * Файлы полностью управляются консолью: управляемым считается файл с маркером;
 * чужие файлы синк не трогает и не удаляет.
 */

const MARKER = "<!-- generated by harness console - файл перезаписывается синком команд -->";

export interface CommandSyncTarget {
  runtime: string;
  /** Каталог команд/навыков относительно обязательной рабочей папки. */
  commandsDir: string;
  /** Плоские имена файлов: рантайм не поддерживает подпапки-пространства имён. */
  flat: boolean;
  /** Форма доставки: команды (.md) или навыки (каталог <имя>/SKILL.md). */
  kind: "commands" | "skills";
  /** Префикс вызова в рантайме (у kimi навык вызывается как /skill:<имя>). */
  invocationPrefix: string;
  /** Подстановка задачи: "$ARGUMENTS" в теле или текст после вызова команды. */
  argumentsMode: "placeholder" | "post-call";
}

/**
 * Рантаймы с проектными каталогами команд и навыков. Файлы команд (claude,
 * zcode, cursor, opencode) кладутся в каталоги команд; codex и kimi командных
 * каталогов не имеют - там те же команды доставляются навыками и вызываются
 * слэшем (codex - "/<имя>", kimi - "/skill:<имя>").
 */
export const COMMAND_SYNC_TARGETS: CommandSyncTarget[] = [
  { runtime: "claude", commandsDir: ".claude/commands", flat: false, kind: "commands", invocationPrefix: "/", argumentsMode: "placeholder" },
  { runtime: "zcode", commandsDir: ".zcode/commands", flat: false, kind: "commands", invocationPrefix: "/", argumentsMode: "placeholder" },
  { runtime: "cursor", commandsDir: ".cursor/commands", flat: true, kind: "commands", invocationPrefix: "/", argumentsMode: "placeholder" },
  { runtime: "opencode", commandsDir: ".opencode/command", flat: true, kind: "commands", invocationPrefix: "/", argumentsMode: "placeholder" },
  { runtime: "codex", commandsDir: ".codex/skills", flat: true, kind: "skills", invocationPrefix: "/", argumentsMode: "post-call" },
  { runtime: "kimi", commandsDir: ".kimi-code/skills", flat: true, kind: "skills", invocationPrefix: "/skill:", argumentsMode: "placeholder" },
];

export interface PlannedCommand {
  /** Путь файла относительно каталога команд рантайма. */
  relFile: string;
  /** Вызов в рантайме. */
  invocation: string;
  kind: "master" | "master-index" | "workflow" | "workflow-index";
  id?: string;
  title: string;
  content: string;
}

/** Имя файла и форма вызова команды по рантайму: подпапка даёт двоеточие в имени,
 * навыки кладутся в каталог <имя>/SKILL.md. Двоеточие в id заменяется точкой
 * (та же конвенция имён файлов workflow, что у консоли). */
export function runtimeCommandName(
  target: CommandSyncTarget,
  kind: "master" | "workflow",
  id?: string,
): { relFile: string; invocation: string } {
  const safeId = id?.replace(/:/g, ".");
  if (target.kind === "skills") {
    const prefix = target.invocationPrefix;
    return safeId
      ? { relFile: `${kind}-${safeId}/SKILL.md`, invocation: `${prefix}${kind}-${safeId}` }
      : { relFile: `${kind}/SKILL.md`, invocation: `${prefix}${kind}` };
  }
  if (target.flat) {
    return safeId
      ? { relFile: `${kind}-${safeId}.md`, invocation: `/${kind}-${safeId}` }
      : { relFile: `${kind}.md`, invocation: `/${kind}` };
  }
  return safeId
    ? { relFile: `${kind}/${safeId}.md`, invocation: `/${kind}:${safeId}` }
    : { relFile: `${kind}.md`, invocation: `/${kind}` };
}

function frontmatter(description: string, argumentHint: string): string {
  return ["---", `description: ${JSON.stringify(description)}`, `argument-hint: ${JSON.stringify(argumentHint)}`, "---"].join("\n");
}

/** Секция задачи: подстановка $ARGUMENTS или указание на текст после вызова. */
function taskSection(target: CommandSyncTarget, label: string): string {
  return target.argumentsMode === "placeholder"
    ? `${label}\n\n$ARGUMENTS`
    : `${label} - текст, следующий за вызовом команды; если его нет - запроси задачу.`;
}

/** Обёртка файла: командный .md (маркер первым) или SKILL.md (frontmatter первым, маркер следом). */
function commandFile(
  target: CommandSyncTarget,
  opts: { name: string; description: string; argumentHint?: string; body: string[] },
): string {
  if (target.kind === "skills") {
    return ["---", `name: ${opts.name}`, `description: ${JSON.stringify(opts.description)}`, "---", "", MARKER, "", ...opts.body, ""].join("\n");
  }
  return [MARKER, "", frontmatter(opts.description, opts.argumentHint ?? "<задача>"), "", ...opts.body, ""].join("\n");
}

const GUARD_NOTE = "Правила AGENTS.md и guard-политика репозитория обязательны.";
const NATIVE_NOTE = "Нативный запуск - упрощение: полный цикл с контролами, рантаймами узлов и журналом выполняет консоль.";

function masterCommandBody(target: CommandSyncTarget, fileBase: string, skillId: string, title: string): string {
  return commandFile(target, {
    name: fileBase,
    description: `${title} - harness master skill`,
    body: [
      `Прочитай файл навыка и точно следуй инструкции из него: .agents/skills/master/skills/${skillId}/SKILL.md`,
      "",
      taskSection(target, "Задача пользователя:"),
      "",
      GUARD_NOTE,
    ],
  });
}

function workflowCommandBody(target: CommandSyncTarget, fileBase: string, workflowFile: string, title: string): string {
  return commandFile(target, {
    name: fileBase,
    description: `${title} - harness workflow`,
    body: [
      `Выполни процесс, определённый в workflow-файле: ${workflowFile}`,
      "Порядок узлов задаёт dependsOn. Роли узлов описаны в .agents/roles, инструкции узла - в execution.prompt, критерии готовности - в inputControl.dor и outputControl.dod. Выполняй узлы последовательно, работая в роли, назначенной узлу.",
      "",
      taskSection(target, "Задача пользователя (input.request):"),
      "",
      GUARD_NOTE,
      NATIVE_NOTE,
    ],
  });
}

function masterIndexBody(target: CommandSyncTarget): string {
  return commandFile(target, {
    name: "master",
    description: "Harness master skill - выбор навыка по задаче",
    argumentHint: "[<id навыка>] <задача>",
    body: [
      'Аргументы: "<id> <задача>" или только "<задача>".',
      "Каталоги навыков: .agents/skills/master/skills/<id>/SKILL.md (общие навыки, у каждого каталога есть manifest.yaml) и .agents/skills/design/skills/<id>/SKILL.md (дизайн-навыки).",
      "Если первый токен аргументов совпадает с именем каталога - следуй SKILL.md этого навыка. Иначе выбери навык, описание и теги в manifest.yaml которого лучше соответствуют задаче, и следуй его SKILL.md.",
      "",
      taskSection(target, "Задача пользователя:"),
      "",
      GUARD_NOTE,
    ],
  });
}

function workflowIndexBody(target: CommandSyncTarget): string {
  return commandFile(target, {
    name: "workflow",
    description: "Harness workflow - запуск процесса по определению",
    argumentHint: "<id> <задача>",
    body: [
      'Аргументы: "<id> <задача>". Каталог процессов: .agents/skills/master/workflows/<id>.yaml.',
      "Прочитай указанный YAML. Порядок узлов задаёт dependsOn; роли узлов описаны в .agents/roles, инструкции узла - в execution.prompt, критерии готовности - в inputControl.dor и outputControl.dod. Выполняй узлы последовательно, работая в роли, назначенной узлу.",
      "",
      taskSection(target, "Задача пользователя (input.request):"),
      "",
      GUARD_NOTE,
      NATIVE_NOTE,
    ],
  });
}

/**
 * Желаемый набор команд по рантаймам: общие /master и /workflow, по команде на
 * каждый master/design-навык, включённый для рантайма (привязка manifest.runtimes
 * и эффективный тоггл), и по команде на каждый workflow каталога.
 */
export async function planRuntimeCommands(repoRoot: string, state: ConsoleStateLike): Promise<Map<string, PlannedCommand[]>> {
  const [internal, workflowCatalog] = await Promise.all([loadInternalSkills(repoRoot), loadWorkflowCatalog(repoRoot)]);
  const workflows = [...workflowCatalog.values()];
  const result = new Map<string, PlannedCommand[]>();
  for (const target of COMMAND_SYNC_TARGETS) {
    const commands: PlannedCommand[] = [
      { ...runtimeCommandName(target, "master"), kind: "master-index", title: "Master skills", content: masterIndexBody(target) },
      { ...runtimeCommandName(target, "workflow"), kind: "workflow-index", title: "Workflows", content: workflowIndexBody(target) },
    ];
    for (const item of internal) {
      if (!skillBoundTo(item.value.runtimes, [target.runtime])) continue;
      const toggleId = (item.group === "design" ? "design:" : "master:") + item.value.id;
      if (!skillEffective(state, toggleId, target.runtime)) continue;
      const name = runtimeCommandName(target, "master", item.value.id);
      const fileBase = target.kind === "skills" ? name.relFile.replace(/\/SKILL\.md$/, "") : target.runtime;
      commands.push({
        ...name,
        kind: "master",
        id: item.value.id,
        title: item.value.title,
        content: masterCommandBody(target, target.kind === "skills" ? fileBase : item.value.id, item.value.id, item.value.title),
      });
    }
    for (const workflow of workflows) {
      // фактический путь YAML: workspace- и id-независимое имя может отличаться от конструируемого
      const relSource = path.relative(repoRoot, workflow.sourceFile);
      const workflowFile = relSource.startsWith("..") ? `.agents/skills/master/workflows/${workflow.value.id}.yaml` : relSource;
      const name = runtimeCommandName(target, "workflow", workflow.value.id);
      const fileBase = target.kind === "skills" ? name.relFile.replace(/\/SKILL\.md$/, "") : "workflow";
      commands.push({
        ...name,
        kind: "workflow",
        id: workflow.value.id,
        title: workflow.value.title,
        content: workflowCommandBody(target, fileBase, workflowFile, workflow.value.title),
      });
    }
    result.set(target.runtime, commands);
  }
  return result;
}

/** Отчёт синка одного рантайма. */
export interface CommandSyncReport {
  runtime: string;
  commandsDir: string;
  written: string[];
  removed: string[];
  error?: string;
}

/** Управляемый файл: содержит маркер синка (у skills-файлов маркер стоит после frontmatter). */
async function isManagedFile(file: string): Promise<boolean> {
  const text = await readFile(file, "utf8").catch(() => "");
  return text.includes(MARKER);
}

/**
 * Полная регенерация управляемых команд в обязательной рабочей папке:
 * недостающие и изменившиеся файлы записываются, управляемые файлы вне плана
 * удаляются. Чужие файлы каталога не изменяются.
 */
export async function syncRuntimeCommands(repoRoot: string, state: ConsoleStateLike): Promise<CommandSyncReport[]> {
  const planned = await planRuntimeCommands(repoRoot, state);
  const reports: CommandSyncReport[] = [];
  for (const target of COMMAND_SYNC_TARGETS) {
    const dir = path.join(repoRoot, target.commandsDir);
    const report: CommandSyncReport = { runtime: target.runtime, commandsDir: target.commandsDir, written: [], removed: [] };
    try {
      const desired = new Map((planned.get(target.runtime) ?? []).map((command) => [command.relFile, command]));
      await mkdir(dir, { recursive: true });
      const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
      if (target.kind === "skills") {
        // навыки: верхний уровень - каталоги <имя>/SKILL.md; чужие каталоги не трогаем
        for (const entry of entries) {
          if (!entry.isDirectory()) continue;
          const relFile = `${entry.name}/SKILL.md`;
          const file = path.join(dir, entry.name, "SKILL.md");
          if (desired.has(relFile) || !(await isManagedFile(file))) continue;
          await rm(path.join(dir, entry.name), { recursive: true, force: true });
          report.removed.push(`${target.commandsDir}/${relFile}`);
        }
      } else {
        for (const entry of entries) {
          if (entry.isDirectory()) {
            // подпапка пространства имён (master/, workflow/): удаляем только управляемые файлы вне плана
            const inner = await readdir(path.join(dir, entry.name), { withFileTypes: true }).catch(() => []);
            for (const innerEntry of inner) {
              if (!innerEntry.isFile() && !innerEntry.isSymbolicLink()) continue;
              if (!innerEntry.name.endsWith(".md")) continue;
              const relFile = `${entry.name}/${innerEntry.name}`;
              const file = path.join(dir, relFile);
              if (desired.has(relFile) || !(await isManagedFile(file))) continue;
              await rm(file);
              report.removed.push(`${target.commandsDir}/${relFile}`);
            }
            continue;
          }
          if (!entry.isFile() && !entry.isSymbolicLink()) continue;
          if (!entry.name.endsWith(".md")) continue;
          const file = path.join(dir, entry.name);
          if (desired.has(entry.name) || !(await isManagedFile(file))) continue;
          await rm(file);
          report.removed.push(`${target.commandsDir}/${entry.name}`);
        }
      }
      for (const command of desired.values()) {
        const file = path.join(dir, command.relFile);
        await mkdir(path.dirname(file), { recursive: true });
        const current = await readFile(file, "utf8").catch(() => null);
        if (current === command.content) continue;
        await writeFile(file, command.content, "utf8");
        report.written.push(`${target.commandsDir}/${command.relFile}`);
      }
    } catch (error) {
      report.error = error instanceof Error ? error.message : String(error);
    }
    reports.push(report);
  }
  return reports;
}

/** Статус команды для UI: файл на месте и совпадает с планом. */
export interface CommandSyncStatusEntry {
  invocation: string;
  file: string;
  title: string;
  present: boolean;
}

export interface CommandSyncStatus {
  runtime: string;
  commandsDir: string;
  commands: CommandSyncStatusEntry[];
  error?: string;
}

/** Статус синка без записи: какие команды должны быть и что фактически в каталоге. */
export async function commandSyncStatus(repoRoot: string, state: ConsoleStateLike): Promise<CommandSyncStatus[]> {
  const planned = await planRuntimeCommands(repoRoot, state);
  const statuses: CommandSyncStatus[] = [];
  for (const target of COMMAND_SYNC_TARGETS) {
    const status: CommandSyncStatus = { runtime: target.runtime, commandsDir: target.commandsDir, commands: [] };
    try {
      for (const command of planned.get(target.runtime) ?? []) {
        const current = await readFile(path.join(repoRoot, target.commandsDir, command.relFile), "utf8").catch(() => null);
        status.commands.push({
          invocation: command.invocation,
          file: `${target.commandsDir}/${command.relFile}`,
          title: command.title,
          present: current === command.content,
        });
      }
    } catch (error) {
      status.error = error instanceof Error ? error.message : String(error);
    }
    statuses.push(status);
  }
  return statuses;
}
